# Generated by Django 3.1.2 on 2020-11-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='urlls',
            field=models.CharField(default='dsdfs', max_length=2500),
            preserve_default=False,
        ),
    ]
