# Generated by Django 3.1.2 on 2020-11-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0003_project_urlls'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='filetype',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='resfile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
