# Generated by Django 3.1.2 on 2020-11-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0004_auto_20201104_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resfile',
            field=models.ImageField(default='h', upload_to='images/'),
            preserve_default=False,
        ),
    ]
