# Generated by Django 3.1.2 on 2020-11-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0005_auto_20201105_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resfile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
