# Generated by Django 3.1.2 on 2020-11-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0006_auto_20201105_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='image',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resfile',
        ),
        migrations.AddField(
            model_name='resume',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
